### PR TITLE
Direct state in context

### LINKED ISSUE #15: Concurrent mode?
From the comment by @MrWolfZ : https://github.com/reduxjs/react-redux/issues/1179#issuecomment-477280690

> it makes render impure since through the proxy it writes to a mutable reference (yes, it only assigns ref.current inside effects but e.g. trapped.reset() etc. during render mutate the objects inside those references); that said, while this means it is not strictly pure, all mutations your library currently performs are "predictable" and reproducible, so the render still has the pure property of same inputs = same outputs

That's what I thought. Not technically pure, but reproducible. So, flushing rendering results in concurrent mode is fine.
Note: WeakMaps are there for performance reasons. It works without them.

> Final note regarding concurrent mode: As @markerikson noted in a source code comment, I believe as well that any solution which accesses store.getState() during render will have issues with concurrent mode, which includes your library.

That's something I thought doubtful too. Let me learn about it.

### PR DESCRIPTION
**Pull request by dai-shi**
As it went well in https://github.com/dai-shi/react-tracked, I'm trying the same technique in reactive-react-redux too.

We put redux state in context and set observedBits = 0.
This should hopefully resolve the concurrent mode issue (but who knows what is concurrent mode...)
Closes #15, unless we further see other concurrent mode issues (in this case file a new issue).

### CODE REVIEW

**Comment by dai-shi** [comment]
So, it slightly decreases performance especially in "select row".

I'll take a deeper look later. Maybe, it can't be helped.

**Comment by dai-shi** [comment]
@markerikson You might have some technical interests in this. I'm not sure how react-redux v6 is implemented at code level, but what I'm trying here is to put `state` in context and still using subscription model. It doesn't seem to gain performance, but hopefully it's concurrent mode friendly.

**Comment by markerikson** [comment]
I would generally expect that propagating state via context is going to be a noticeable drop in performance.  because that's what we saw with v6.

**Comment by dai-shi** [comment]
@markerikson It's not that bad. I think it's different from rr v6, in which context propagate all components and HoCs stop updating. Whereas, this one, context doesn't propagate, but calls listeners in `batchedUpdates`. Probably, the batchedUpdates is important for performance.

**Comment by dai-shi** [comment]
> Probably, the batchedUpdates is important for performance.

This is not correct in this case, because it is in useEffect.

**Comment by dai-shi** [comment]
Run js-framework-benchmark again. This time, the control is react-redux v7.1.0.

I'm pretty confident that performances are fine.

Only the comparison is:
- reactive-react-redux v3.0.0 uses store context with `unstable_batchedUpdates` for correctness and performance
- reactive-react-redux v4.0.0-alpha.2 uses more or less state context with `unstable_calculateChangedBits` to avoid context propagation

Which is better? A hard question. Anyone have comments? Our hero @gaearon

----

**Comment by dai-shi** [comment]
My intuition is go for it.

I would expect when React would drop the `observedBits` feature, it should provide other method to bail out useContext.

I would appreciate for any comments even after this PR is merged. Thanks.

**Pull request merged**
